### ISSUE TITLE
Product link

### ISSUE THREAD

**Issue by bettse** [adafruit/Adafruit_MFRC630#1]
I feel silly for asking, but I can't find any links to the product on adafruit, or even anything about if it used to be a product and was discontinued.  Is their any details that may shed light on this?

**Comment by bettse** [comment]
Well, obviously immediately after asking, I find a forum link about the topic from roughly a year ago: https://forums.adafruit.com/viewtopic.php?f=19&t=148080

**Comment by ladyada** [comment]
this product has not been released, there is no ETA
